config/routes.rb
Rbc::Application.routes.draw do
  root :to => 'home#index'

  resources :users, :only => :create
  resources :questionaries, :only => :create

  match '/location' => 'home#location', as: :location
  match '/program' => 'home#program', as: :program
  match '/register' => 'registrations#new', as: :new_registration
  match '/schedule' => 'home#schedule', as: :schedule

  resources :registrations, only: [:new, :create] do
    collection do
      get :success
    end
  end

  namespace :admin do
    root to: 'dashboard#show'
    resource :dashboard, controller: 'dashboard'
    resources :users
    resources :registrations do
      member do
        post :confirm
      end
    end
  end

  if Rails.application.config.consider_all_requests_local
    get "errors/error_404"
    get "errors/error_500"
  else
    match '*not_found', to: 'errors#error_404'
  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/questionary.rb
# encoding: utf-8

class Questionary
  include Mongoid::Document
  include Mongoid::Timestamps

  LANGUAGES = [
    'C / C++',
    'C#',
    'Java',
    'PHP',
    'Python',
    'Ruby'
  ]

  EXPERIENCE = [
    'нет опыта',
    'меньше года',
    '1-2 года',
    '3-6 лет',
    'больше 6-ти лет'
  ]

  scope :by_language,   lambda { |value| any_of(:languages => value) }
  scope :by_experience, lambda { |value| any_of(:experience => value) }

  field :user_id, type: Integer
  field :languages, type: Array
  field :experience, type: Array
end

app/models/registration.rb
class Registration
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessible :email, :name, :status

  field :email, type: String
  field :name, type: String
  field :status, type: String, default: 'new'

  validates :name, presence: true
  validates :email, :presence => true, uniqueness: true, format: {:with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }

  scope :confirmed, where(status: 'confirmed')

  def confirmed?
    status == 'confirmed'
  end

end

app/models/statistics.rb
class Statistics
  def languages
    @languages ||= begin
      Questionary::LANGUAGES.inject({}) do |result, language|
        result[language] = Questionary.by_language(language).count
        result
      end
    end
  end

  def experience
    @experience ||= begin
      Questionary::EXPERIENCE.inject({}) do |result, experience|
        result[experience] = Questionary.by_experience(experience).count
        result
      end
    end
  end

  def count
    @count ||= Questionary.count
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email
  validates :email, :presence => true, uniqueness: true, format: {:with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }

  def self.find_or_create_by_email(email)
    where(email: email).first || create(email: email)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate, lambda { |c| !Rails.env.test? }

  layout 'admin'

  protected

  def authenticate
    if user = authenticate_with_http_basic { |u, p| validate_password(u, p) }
      @current_user = user
    else
      request_http_basic_authentication
    end
  end

  def validate_password(u, p)
    u == 'admin' && p == AppConfig['admin_password']
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def show
    @users = User.all
    @questions = Questionary.all
  end

end

app/controllers/admin/registrations_controller.rb
#encoding: utf-8

require 'csv'

class Admin::RegistrationsController < Admin::BaseController

  def index
    respond_to do |format|
      format.html do
        @registrations = Registration.desc(:created_at).all
      end

      format.csv do
        filename = 'registrations.csv'

        headers["Content-Type"] ||= 'text/csv'
        headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
        headers["Content-Transfer-Encoding"] = 'binary'

        csv_string = CSV.generate do |csv|
          csv << ['Name', 'Email']
          Registration.all.each do |reg|
            csv << [reg.name, reg.email]
          end
        end
        render :text => csv_string
      end
    end
  end



  def confirm
    @registration = Registration.find params[:id]

    if @registration.update_attributes status: 'confirmed'
      UserMailer.confirm(@registration).deliver
      redirect_to :back, notice: 'Статус подтвержден'
    else
      redirect_to :back, error: 'Failed to update status'
    end
  end

  def destroy
    @reg = Registration.find params[:id]

    if @reg.destroy
      UserMailer.cancel(@reg).deliver

      redirect_to :back, notice: 'Регистрация удалена'
    else
      redirect_to :back, error: 'Регистрация не была удалена'
    end
  end
end

app/controllers/admin/users_controller.rb
require 'csv'

class Admin::UsersController < Admin::BaseController

  def index
    respond_to do |format|
      format.csv do

        filename = 'subscribers.csv'

        headers["Content-Type"] ||= 'text/csv'
        headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
        headers["Content-Transfer-Encoding"] = "binary"

        csv_string = CSV.generate do |csv|
          csv << ["Email"]
          User.all.each do |user|
            csv << [user.email]
          end
        end
        render :text => csv_string
      end
    end
  end

  def destroy
    @user = User.find params[:id]
    if @user.destroy
      redirect_to :back, notice: 'Successfully deleted'
    else
      redirect_to :back, error: 'Error deleting user'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: lambda { |exception| render_error 500, exception }
    rescue_from ActionController::RoutingError, ActionController::UnknownController,
                ::AbstractController::ActionNotFound, with: lambda { |exception| render_error 404, exception }
  end

  private
  def render_error(status, exception)
    respond_to do |format|
      format.html { render template: "errors/error_#{status}", layout: 'layouts/application', status: status }
      format.all { render nothing: true, status: status }
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error_404
    @not_found_path = params[:not_found]
  end

  def error_500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
    @questionary = Questionary.new
  end
end

app/controllers/questionaries_controller.rb
class QuestionariesController < ApplicationController
  def create
    Questionary.create(params[:questionary])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @opened = false
    @registration = Registration.new email: params[:email]
  end

  def create
    @registration = Registration.new params[:registration]

    if @registration.save
      UserMailer.registration(@registration).deliver
      redirect_to action: :success
    else
      render :new
    end
  end

  def success

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.find_or_create_by_email(params[:email])
    if @user.persisted?
      UserMailer.welcome(@user.email).deliver
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages(flash)
    html = ''
    flash.each do |key, msg|
      html << content_tag('div', class: "alert alert-#{key}") do
        content_tag('button', 'x', class: 'close', 'data-dismiss' => 'alert', type: 'button') + msg
      end
    end
    html.html_safe
  end

end

app/views/admin/dashboard/show.html.haml
.container
  .row
    .span6
      .page-header
        %h2 Подписались

      %p.mute
        == #{@users.count} подписчиков:

      - if @users.any?
        %table.table
          - @users.each do |user|
            %tr
              %td= user.email
              %td= time_ago_in_words(user.created_at) + ' ago' unless user.created_at.blank?
              %td= link_to 'delete', [:admin, user], method: 'delete', 'data-confirm' => "Are you sure you want to delete '#{user.email}'?"

        = link_to 'Экспорт', admin_users_path(format: 'csv')
      - else
        нет подписавшихся

    .span6
      .page-header
        %h2 Опыт

      %p.mute
        == #{@questions.count} ответов:

      - if @questions.any?
        %table.table
          %tr
            %th Опыт
            %th Языки
          - @questions.each do |q|
            - unless q.experience.blank?
              %tr
                %td= q.experience
                %td= q.languages.to_a.join(', ')

app/views/home/_gallery.html.haml
#gallery.carousel.slide
  %ol.carousel-indicators
    - (0..28).each do |n|
      %li{'data-target'=>"#gallery", 'data-slide-to' => "#{n.to_s.rjust(2, '0')}", :class => n == 0 ? 'active' : '' }

  .carousel-inner
    - (0..28).each do |n|
      .item{:class => n == 0 ? 'active' : ''}
        = image_tag "photos/#{n.to_s.rjust(2, '0')}.jpg"

  %a{:class=>"carousel-control left", :href=>"#gallery", 'data-slide'=>"prev"} &lsaquo;
  %a{:class=>"carousel-control right", :href=>"#gallery", 'data-slide'=>"next"} &rsaquo;

app/views/home/_questions.html.haml
#questionary.modal.hide.fade{ role:'dialog', 'aria-labbeled-by' => 'modal_label', 'aria-hidden' => false }

  = form_for @questionary, :remote => true, :html => { :class => 'form-vertical' } do |f|

    .modal-header
      %button{ type:"button", class:"close", 'data-dismiss'=>"modal", 'aria-hidden'=>"true" } &times;
      %h3#model_label Спасибо за проявленный интерес!

    .modal-body

      %h4
        Мы будем очень благодарны, если ты ответишь на пару вопросов.
        Это поможет нам сделать программу курсов интереснее и полезнее.

      .control-group
        = f.label :language, "Какие языки программирования ты знаешь?", :class => 'control-label'
        .controls
          - Questionary::LANGUAGES.each do |language|
            %label.checkbox
              = check_box_tag 'questionary[languages][]', language
              = language
      .control-group
        = f.label :experience, 'Сколько лет ты программируешь?', :class => 'control-label'
        .controls
          - Questionary::EXPERIENCE.each do |experience|
            %label.radio
              = f.radio_button :experience, experience
              = experience

    .modal-footer
      = f.submit 'Отправить', class: 'btn btn-primary'

app/views/home/_subscribe.html.haml
.subscribe
  = form_for @user, :remote => true, :html => { :class => 'form-horizontal' } do |f|

    %p
      %strong Я хочу получать новости о курсе "Ruby on Rails: быстрый старт"

    = email_field_tag :email, '', :class => 'span3', :required => true, :placeholder => 'Электропочта'
    = f.submit 'Подписаться', :class => 'btn btn-red', 'data-disable-with' => 'Подождите...'
    %br
    %small.mute Мы не будем вас спамить и не передадим информацию посторонним.

  #thankyou.hide
    %h4 Спасибо! Мы напишем тебе сразу, как только у нас будут новости.

app/views/home/_target.html.haml
.row-fluid.target
  .span6
    %h4 Начинающим
    %p
      Ruby - это прекрасный язык для того, чтобы начать программировать. А Ruby on Rails научит тебя правильным
      подходам к программированию, такие как модульность, расширяемость и тестирование.
  .span6
    %h4 Опытным
    %p
      Если ты пишешь на PHP, Python или C#, тебе будет интересно познакомиться с новым языком - Ruby.
      Это красивый, мощный и удобный язык. Ruby on Rails - это мощная инфраструктура, которая делает твою работу приятной и продуктивной.

app/views/home/index.html.haml
.jumbotron
  .container-narrow
    %h1
      Ruby on Rails:
      %br
      Быстрый старт
    %p.lead
      Познакомься с замечательным фреймворком для создания веб приложений.
      Начни использовать Rails в реальных проектах уже завтра.



.container-narrow
  = render 'gallery'

  .row-fluid
    .span12.program
      Команда разработчиков компании Kodo Labs провела 2-х дневные курсы по Ruby on Rails в Севастополе.

      Программа совместила в себе теорию и практику. Слушатели узнали как быстро настроить рабочее окружение, как устроено rails-приложение,
      как работать с базами данных и как писать автоматизированные тесты.


  = render 'subscribe'

  -#.registration_teaser
  -#  = link_to 'Регистрация', new_registration_path, class: 'btn btn-red'

  -#= render 'target'

-#= render 'questions'


:javascript
  $('#questionary').on('hidden', function() {
    $("#new_user").fadeOut('fast', function() {
      $('#thankyou').fadeIn();
    });
  });

app/views/home/location.html.haml
.container-narrow
  %section
    %h2 Место проведения

    %p
      Конференц-зал отеля Рейкарц
      %br
      ул. Героев Сталинграда, 22

    %p
      %strong Начало регистрации: 15 июня в 9:30


  #map-canvas

= content_for :javascript do
  :javascript

    var map;
    function initializeMap() {
      var mapOptions = {
        zoom: 17,
        center: new google.maps.LatLng(44.582415,33.434897),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById('map-canvas'),
          mapOptions);
    }

    google.maps.event.addDomListener(window, 'load', initializeMap);

app/views/home/program.html.haml
.container-narrow

  %section
    %h2 Программа

    %p
      Курсы пройдут в форме интенсивного двухдневного семинара 15-16 июня в конференц-зале гостиницы Рейкарц
      (ул Героев Сталинграда, 22) с 10 до 17 часов. Стоимость участия - 200 грн. Количество мест ограничено - 20 человек.

  %section
    %h2 Кто мы и зачем это делаем

    %p
      Курсы
      %strong Ruby on Rails: Быстрый старт
      организованы командой Kodo Labs - профессиональными разработчиками
      с 4-х летним стажем работы с Ruby on Rails.

    %p
      Мы считаем что несмотря на огромную популярность Ruby on Rails в мире, в нашем городе
      немногие знают о нем и мы хотим исправить эту ситуацию.

    %p
      Мы хотим поделиться своим опытом и помочь тебе начать программировать на ruby и
      использовать замечательный фреймворк Ruby on Rails в своих проектах.

  %section
    %h2 Для кого мы это делаем

    %p
      Эти курсы рассчитаны на людей, которые уже умеют программировать хотя бы на одном языке и, желательно,
      знакомы с основами веб-программирования.
      Наиболее интересно будет опытным программистам, которые разрабатывают веб-приложения на PHP, .NET,
      JAVA или Python. Они смогут сравнить и оценить премущества, которые дает Rails.

    %p
      Если ты начинающий программист, то ты не должен бояться командной строки, быть хотя бы немного знаком
      с линуксом и понимать чем отличается GET от POST.

    %p Чтобы получить максимальную пользу, тебе стоит прийти с ноутбуком. Если у тебя нет своего, попроси на время у друга.

  %section
    %h2 Формат и темы

    %p
      Двух-дневный интенсивный курс будет включать в себя теорию, практику, скринкасты и сессию вопросов-ответов.
      Мы поможем установить на твой ноутбук все необходимое для работы. Мы вместе с тобой разработаем
      несложное приложение и расскажем обо всем, что тебе понадобится для работы с Rails.

    %ul
      %li Архитектура Rails
      %li Использование генераторов для создания приложения и отдельных компонентов
      %li git - отличия, преимущества. Работа с ветками.
      %li ActiveRecord - модели, миграции, валидация, ассоциации.
      %li Фронтэнд - views, helpers
      %li Аsset pipeline
      %li Тестирование
      %li Популярные библиотеки - ruby gems


  %br
  %br
  %br

app/views/home/schedule.html.haml
.container-narrow

  %section
    %h2 Подготовка

    %p
      Настройка ноутбука для работы ruby & rails может занять некоторое время, к тому же, настройка окружения под Windows
      это совсем нелегкая задача, поэтому мы приготовили образ виртуальной машины с Xubuntu, где уже все настроено.
      Для того чтобы использовать этот образ тебе надо скачать и установить бесплатный
      == #{link_to 'VirtualBox', 'https://www.virtualbox.org/wiki/Downloads'}, затем скачать
      образ виртуальной машины
      == #{link_to 'railskickstart.vdi', 'https://www.dropbox.com/s/klprak41k2guqwd/railskickstart.vdi'} (4.5 ГБ).

    %p
      Затем надо создать новую виртуальную машину с использованием этого VDI файла.
      == Подробная инструкция на английском #{link_to 'здесь', 'https://www.virtualbox.org/manual/ch01.html#gui-createvm'}.

  %section
    %h2 Расписание

    %p Каждый день курсов будет по пять презентаций.

    %p
      %strong День первый

    %table.table
      %tr
        %td{width: '20%'} 9:30 - 10:00
        %td регистрация, настройка
      %tr
        %td 10:00 - 10:20
        %td приветствие
      %tr
        %td 10:20 - 11:05
        %td Ruby
      %tr
        %td 11:15 - 12:00
        %td Environment
      %tr
        %td
        %td coffee break
      %tr
        %td 12:15 - 13:15
        %td ActiveRecord

      %tr
        %td 13:30 - 14:30
        %td обед
      %tr
        %td 14:30 - 15:15
        %td ActionController
      %tr
        %td 15:30 - 16:15
        %td ActionView


    %p
      %strong День второй

    %table.table
      %tr
        %td{width: '20%'}  10:00 - 10:45
        %td ActionController 2 + REST
      %tr
        %td 11:00 - 11:45
        %td ActiveRecord 2
      %tr
        %td
        %td coffee break
      %tr
        %td 12:00 - 12:45
        %td Тестирование
      %tr
        %td 13:30 - 14:30
        %td перерыв на обед
      %tr
        %td 14:30 - 15:15
        %td Assets
      %tr
        %td 15:30 - 16:15
        %td Полезные библиотеки


  %br
  %br
  %br

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40873059-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-narrow
      %ul.nav
        %li= link_to 'Главная', root_path
        %li= link_to 'Программа', program_path
        %li= link_to 'Место', location_path
        %li= link_to 'Расписание', schedule_path

      %ul.nav.pull-right
        %li= link_to 'Регистрация', new_registration_path, class: 'important'

app/views/layouts/_navbar_admin.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        %li= link_to 'Главная', admin_dashboard_path
        %li= link_to 'Регистрации', admin_registrations_path

app/views/layouts/_social-likes.html.erb
<ul class="social-likes" data-title="Курсы &quot;Ruby on Rails: Быстрый старт&quot; в Севастополе">
  <li class="facebook" title="Поделиться ссылкой на Фейсбуке">Facebook</li>
  <li class="twitter" title="Поделиться ссылкой в Твиттере">Twitter</li>
  <li class="plusone" title="Поделиться ссылкой в Гугл-плюсе">Google+</li>
  <li class="vkontakte" title="Поделиться ссылкой во Вконтакте">Вконтакте</li>
</ul>

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}
    %title Railskickstart Admin
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"

    = csrf_meta_tags
  %body

    = render 'layouts/analytics'

    = render 'layouts/navbar_admin'


    #wrap
      = yield
      #push

    %footer
      .container

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}
    %title Курсы "Ruby on Rails: Быстрый старт" в Севастополе
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false'
    %meta{property:"og:type", content:"article"}
    %meta{property:"og:url", content:"http://railskickstart.com.ua/"}
    %meta{property:"og:title", content:"Открыта регистрация на курсы 'Ruby on Rails: Быстрый старт' в Севастополе"}
    %meta{property:"og:description", content:"Познакомься с замечательным фреймворком для создания веб приложений. Начни использовать Rails в реальных проектах уже завтра."}
    %meta{property:"og:image", content:"http://rubyonrails.org/images/rails.png"}
    %meta{name:"twitter:card", content: "Открыта регистрация на курсы 'Ruby on Rails: Быстрый старт' в Севастополе #railskickstart"}
    %meta{name:"twitter:site", content:"http://railskickstart.com.ua/"}
    %meta{name:"twitter:creator", content:"@kodolabs"}

    = yield :javascript

    = csrf_meta_tags
  %body

    = render 'layouts/analytics'

    -#= render 'layouts/navbar'

    #wrap
      = yield
      #push

    %footer
      .container-narrow
        .row-fluid
          .span9
            = render 'layouts/social-likes'

          .span3
            .pull-right
              = link_to 'Kodo Labs', 'http://kodolabs.com'
              &copy; 2013

app/views/questionaries/create.js.erb
$('#questionary').modal('hide');

app/views/users/create.js.erb
<% if @user.persisted? %>
    $('#questionary').modal();
<% else %>
    alert("OMG! Something is wrong!")
<% end %>